# Generated by Django 6.0.6 on 2026-06-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('subject', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('slnumber', models.CharField(default='', max_length=50)),
                ('note_type', models.CharField(default='', max_length=300)),
                ('amount', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=300)),
                ('user_type', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(default='', upload_to='policeimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=300)),
                ('user_type', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(default='', upload_to='currency/')),
                ('note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencyApp.tbl_note')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencyApp.tbl_user')),
            ],
        ),
    ]
